unstable_features = true
indent_style = "Block"
reorder_imports = true
imports_layout = "Mixed"
merge_imports = false
max_width = 120
force_multiline_blocks = false
tab_spaces = 2
trailing_comma = "Vertical"
use_try_shorthand = true

format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
normalize_doc_attributes = true

edition = "2018"
